#!/usr/bin/env python3

import argparse
import csv
from pathlib import Path

from patsyn.domain import load_public_domain
from patsyn.metrics import evaluate_all
from patsyn.preprocessing import load_processed_dataset
from patsyn.synthesis import (
    load_sampled_conditions,
    load_synthetic_dataset,
)
from patsyn.utils import (
    load_config,
    save_json,
    set_seed,
)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Evaluate synthetic trajectories generated by PATSyn."
    )
    parser.add_argument(
        "--config",
        type=str,
        default="configs/porto.yaml",
        help="Dataset configuration file.",
    )
    parser.add_argument(
        "--default-config",
        type=str,
        default="configs/default.yaml",
        help="Default configuration file.",
    )
    parser.add_argument(
        "--epsilon",
        type=float,
        default=None,
        help="Privacy budget used for synthesis.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Random seed.",
    )
    parser.add_argument(
        "--synthetic",
        type=str,
        default=None,
        help="Optional synthetic trajectory file.",
    )
    parser.add_argument(
        "--conditions",
        type=str,
        default=None,
        help="Optional sampled-condition file.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing evaluation results.",
    )
    return parser.parse_args()


def flatten_dict(data, prefix=""):
    flat = {}

    for key, value in data.items():
        name = f"{prefix}.{key}" if prefix else key

        if isinstance(value, dict):
            flat.update(flatten_dict(value, name))
        else:
            flat[name] = value

    return flat


def save_metrics_csv(metrics, metadata, output_path):
    row = {}
    row.update(metadata)
    row.update(flatten_dict(metrics))

    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(
            file,
            fieldnames=list(row.keys()),
        )
        writer.writeheader()
        writer.writerow(row)


def main():
    args = parse_args()

    config = load_config(
        default_path=args.default_config,
        dataset_path=args.config,
    )

    epsilon = (
        args.epsilon
        if args.epsilon is not None
        else float(config["experiment"]["default_epsilon"])
    )

    seed = (
        args.seed
        if args.seed is not None
        else int(config["project"]["seed"])
    )

    if epsilon <= 0:
        raise ValueError("epsilon must be positive.")

    set_seed(seed)

    dataset_name = config["dataset"]["name"]

    processed_dir = Path(config["paths"]["processed_dir"])
    cache_dir = Path(config["paths"]["cache_dir"])
    output_root = Path(config["paths"]["output_dir"])
    result_root = Path(config["paths"]["result_dir"])

    run_dir = (
        output_root
        / f"eps_{epsilon}"
        / f"seed_{seed}"
    )

    result_dir = (
        result_root
        / f"eps_{epsilon}"
        / f"seed_{seed}"
    )

    real_path = processed_dir / "trajectories.pkl"
    domain_path = cache_dir / "public_domain.pkl"

    synthetic_path = (
        Path(args.synthetic)
        if args.synthetic is not None
        else run_dir / "synthetic.pkl"
    )

    conditions_path = (
        Path(args.conditions)
        if args.conditions is not None
        else run_dir / "sampled_conditions.npz"
    )

    metrics_json_path = result_dir / "metrics.json"
    metrics_csv_path = result_dir / "metrics.csv"

    required_files = [
        real_path,
        domain_path,
        synthetic_path,
        conditions_path,
    ]

    for path in required_files:
        if not path.exists():
            raise FileNotFoundError(
                f"Required file does not exist: {path}"
            )

    if metrics_json_path.exists() and not args.overwrite:
        raise FileExistsError(
            f"{metrics_json_path} already exists. "
            "Use --overwrite to replace it."
        )

    result_dir.mkdir(parents=True, exist_ok=True)

    print(f"[PATSyn] Evaluating dataset: {dataset_name}")
    print(f"[PATSyn] epsilon: {epsilon}")
    print(f"[PATSyn] Seed: {seed}")

    real_trajectories = load_processed_dataset(
        real_path
    )

    synthetic_trajectories = load_synthetic_dataset(
        synthetic_path
    )

    sampled_conditions = load_sampled_conditions(
        conditions_path
    )

    public_domain = load_public_domain(
        domain_path
    )

    metrics = evaluate_all(
        real_trajectories=real_trajectories,
        synthetic_trajectories=synthetic_trajectories,
        sampled_conditions=sampled_conditions,
        public_domain=public_domain,
        config=config,
        seed=seed,
    )

    output = {
        "dataset": dataset_name,
        "epsilon": epsilon,
        "seed": seed,
        "num_real": len(real_trajectories),
        "num_synthetic": len(synthetic_trajectories),
        "metrics": metrics,
    }

    save_json(
        output,
        metrics_json_path,
    )

    save_metrics_csv(
        metrics=metrics,
        metadata={
            "dataset": dataset_name,
            "epsilon": epsilon,
            "seed": seed,
            "num_real": len(real_trajectories),
            "num_synthetic": len(synthetic_trajectories),
        },
        output_path=metrics_csv_path,
    )

    print("[PATSyn] Evaluation complete.")

    for group_name, group_metrics in metrics.items():
        print(f"[PATSyn] {group_name}")

        if isinstance(group_metrics, dict):
            for metric_name, value in group_metrics.items():
                if isinstance(value, (int, float)):
                    print(
                        f"  {metric_name}: "
                        f"{value:.6f}"
                    )

    print(f"[PATSyn] Saved: {metrics_json_path}")
    print(f"[PATSyn] Saved: {metrics_csv_path}")


if __name__ == "__main__":
    main()